/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pqcsignature_Sign */

#ifndef _Included_pqcsignature_Sign
#define _Included_pqcsignature_Sign
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pqcsignature_Sign
 * Method:    crypto_sign_keypair
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_pqcsignature_Sign_crypto_1sign_1keypair
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     pqcsignature_Sign
 * Method:    crypto_sign_sign
 * Signature: ([BI[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_pqcsignature_Sign_crypto_1sign_1sign
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     pqcsignature_Sign
 * Method:    crypto_sign_verify
 * Signature: ([BI[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_pqcsignature_Sign_crypto_1sign_1verify
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
